# Generated by Django 4.2.3 on 2023-07-22 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_team_owner_user_id_team_team_name_pretty_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='teammembership',
            table='team_membership',
        ),
    ]
