# Generated by Django 4.2.3 on 2023-07-22 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='hackathon',
            table='hackathon_hackathon',
        ),
        migrations.AlterModelTable(
            name='hackathonaward',
            table='hackathon_award',
        ),
        migrations.AlterModelTable(
            name='hackathonawardvote',
            table='hackathon_award_vote',
        ),
        migrations.AlterModelTable(
            name='hackathonteamenrol',
            table='hackathon_team_enrol',
        ),
        migrations.AlterModelTable(
            name='hackathonuserenrol',
            table='hackathon_user_enrol',
        ),
    ]
