# Generated by Django 4.2.3 on 2023-07-23 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
        ('hackathon', '0002_hackathonteamenrol_uniq_hackathon_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackathonaward',
            name='winner_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='team.team'),
        ),
    ]
